---
title: "Assignment_1a"
author: "Nick McManus"
date: "2023-02-13"
output: html_document
---


## Why I'm taking this course:

I want to continue expanding my knowledge of computing and become more proficient in modular program design. I’m interested in geospatial analysis, remote sensing, and environmental modeling; coming into Bren, I aimed to make a viable career out of these interests. I’m also planning to take the environmental modeling class next quarter, and feel that this class will help provide the skills necessary to succeed in that course.



## Data science background:

Before coming to Bren, I had almost no experience with programming and all data manipulation/visualization was confined to programs such as Excel or ArcGIS. Since coming to Bren, I’ve taken ESM206 (Statistics and Data Analysis) and am currently enrolled in ESM 242 (Advanced Data Analysis). For my Group Project, I’ve learned how to use the geospatial packages in R, such as `terra` and `raster`, as well as the conservation spatial optimization package, `prioritizr`. Additionally, through an internship this past fall I gained experience building user-facing apps and land-use models in Google Earth Engine.
